### ISSUE TITLE
Debian packaging doesn't install tools/dtbo

### ISSUE THREAD

**Issue by malc0** [RobertCNelson/bb.org-overlays#13]
Not having the dtbo script as an initramfs hook means that *.dtbo doesn't get included in the initrd's /lib/firmware by update-initramfs, and bone_capemgr.enable_partno= and friends don't work.

**Comment by RobertCNelson** [comment]
@malc0 for historical reasons it's in the bb-customizations package.

https://github.com/rcn-ee/repos/blob/master/bb-customizations/suite/jessie/debian/dtbo

now that we have a separate overlay package i should merge that script into this repo.

Regards,

**Comment by malc0** [comment]
Aha, thanks for the pointer, and apologies for not filing this against the repos repo.  I'd done a stretch netinstall and ended up with neither bb.org-overlays nor bb-customizations.  Perhaps, if merging the script has any complications, the situation I'd created could be avoided by making bb.org-overlays depend on bb-customizations?

**Comment by RobertCNelson** [comment]
i came up with this:

https://github.com/rcn-ee/repos/blob/master/bb-cape-overlays/suite/jessie/debian/dtbo_bb-cape-overlays

it'll just exit if the old dtbo script exists..

Regards,

**Comment by malc0** [comment]
Thanks, that works a treat.
