### ISSUE TITLE
gpio0_22 or gpio0_23

### ISSUE THREAD

**Issue by fivdi** [RobertCNelson/bb.org-overlays#3]
Because `P8.19` is `gpio0_22`, should `gpio0_23` [here](https://github.com/RobertCNelson/bb.org-overlays/blob/master/src/arm/BB-BONE-BACONE-00A0.dts#L36) actually be `gpio0_22`?

**Comment by RobertCNelson** [comment]
@fivdi correct, feel free to make a merge request against https://github.com/beagleboard/bb.org-overlays to fix it. ;) i missed that change when i fixed the bacon cape..
