### ISSUE TITLE
Build fails in a proxied environment

### ISSUE THREAD

**Issue by QuickJack** [RobertCNelson/bb.org-overlays#39]
The latest change to dtc_overlay.sh (0e3c94072dd98c1cdd877e773be0e68f67479acb) modified the protocol for cloning the dtc tool from https:// to git://. Unfortunately, the git:// protocol cannot be used in a proxied environment.

Is there a specific reason as to why the protocol has been changed?

**Comment by RobertCNelson** [comment]
@QuickJack no real reason... Mainline dtc 1.4.7 or later is required, no patches.. Most dist's should now meet this requirement..

Regards,

**Comment by QuickJack** [comment]
Thanks for the quick fix.
